config/routes.rb
Myapp::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations"  }#, skip: :registrations
  get "home/index"

  root to: 'home#index'
  get 'authenticate/new' => 'authenticate#new'
  resources :users, only:[:index] do
  end

end

app/models/authenticate.rb
class Authenticate
  include ActiveModel::Validations  
  attr_accessor :code
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :name, :phone, :current_job, :address, presence: true
  validates :security_code, presence: true, on: :create
  validates_format_of :security_code, with: /191014280991/, on: :create
  attr_accessor :security_code

  scope :confirmed, -> { where("confirmed_at IS NOT NULL") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :birth_date, :phone, :current_job, :address, :email, :password, :password_confirmation, :security_code)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/authenticate_controller.rb
class AuthenticateController < ApplicationController
  def new
    respond_to do |format|
      format.js   { render partial: "javascript/authenticate" }
      format.html { redirect_to root_path }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
    else
      # remove the virtual current_password attribute
      # update_without_password doesn't know how to ignore it
      params[:user].delete(:current_password)
      @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
    end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case their password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end
  # def create
  #   build_resource(sign_up_params)
  #   authenticate_code = true
  #   if resource.security_code == "191014280991"
  #     resource_saved = resource.save
  #   else
  #     authenticate_code = false  
  #   end
    
  #   yield resource if block_given?
  #   if resource_saved
  #     if resource.active_for_authentication?
  #       set_flash_message :notice, :signed_up if is_flashing_format?
  #       sign_up(resource_name, resource)
  #       respond_with resource, location: after_sign_up_path_for(resource)
  #     else
  #       set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
  #       expire_data_after_sign_in!
  #       respond_with resource, location: after_inactive_sign_up_path_for(resource)
  #     end
  #   else
  #     if authenticate_code
  #       clean_up_passwords resource
  #       @validatable = devise_mapping.validatable?
  #       if @validatable
  #         @minimum_password_length = resource_class.password_length.min
  #       end
  #       respond_with resource
  #     else
  #       render "new"
  #     end
      
  #   end
  # end

  # def create
  #   build_resource(sign_up_params)
  #   # if resource.security_code == "191014280991"
  #   #   authenticate_code = true
  #   # else
  #   #   authenticate_code = false  
  #   # end
  #   resource_saved = resource.save
  #   yield resource if block_given?
  #   if resource_saved
  #     if resource.active_for_authentication?
  #       set_flash_message :notice, :signed_up if is_flashing_format?
  #       sign_up(resource_name, resource)
  #       respond_with resource, location: after_sign_up_path_for(resource)
  #     else
  #       set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
  #       expire_data_after_sign_in!
  #       respond_with resource, location: after_inactive_sign_up_path_for(resource)
  #     end
  #   else
  #     clean_up_passwords resource
  #     @validatable = devise_mapping.validatable?
  #     if @validatable
  #       @minimum_password_length = resource_class.password_length.min
  #     end
  #     respond_with resource
  #   end
  # end

  private

  # check if we need password to update user data
  # ie if password or email was changed
  # extend this as needed
  def needs_password?(user, params)
    user.email != params[:user][:email] ||
      params[:user][:password].present? ||
      params[:user][:password_confirmation].present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:index]

  def index
    @users = User.all.confirmed
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authenticate/new.html.erb
<%= render "form/authenticate"%>

app/views/form/_authenticate.html.erb
<div id="authenticate-form" class="portfolio-area align-center">
  <form class="form-inline" role="form">
    <div class="form-group">
      <label class="sr-only" for="exampleInputEmail2">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
    </div>
    <button type="submit" class="btn btn-info">Submit</button>
  </form>
</div> 

app/views/home/index.html.erb
<div class="pageWrapper">
    <article class="logo-bar">
        <div class="container"> 
            <%= render "layouts/messages" %>
            <!-- Logo -->
            <div class="pull-right"> <span class="nav-button"></span>
                <nav class="main-nav">
                    <%= render "layouts/navigation" %>
                </nav>
            </div>
        </div>
    </article>
    <article class="main-slider">
        <div class="fullwidthbanner">
            <ul>
                <li data-transition="fade" data-slotamount="10" data-masterspeed="1500"> <%= image_tag 'home.jpg' %>
                  <!-- <img src="images/resource/slide-1.jpg" alt="slide 1"> -->
                    <div class="caption lfl stl"
                        data-x="center"
                        data-y="top"
                        data-hoffset="-100"
                        data-voffset="350"
                        data-speed="500"
                        data-start="1500"
                        data-easing="easeOutExpo">
                        <% if user_signed_in? %>
                            <%= link_to "Edit Profile", edit_user_registration_path,  class: "btn btn-transparent" %>
                        <% else %>
                            <%= link_to "Register", new_user_registration_path,  class: "btn btn-transparent" %>
                        <% end %>
                    </div>
                    <div class="caption lfr str"
                        data-x="center"
                        data-y="top"
                        data-hoffset="100"
                        data-voffset="350"
                        data-speed="500"
                        data-start="1500"
                        data-easing="easeOutExpo">
                        <% if user_signed_in? %>
                            <%= link_to destroy_user_session_path,  class: "btn btn-transparent", method: :delete do %>Logout<% end %>
                        <% else %>
                            <%= link_to "Login", user_session_path,  class: "btn btn-transparent" %>
                        <% end %>
                    </div>
                </li>
                <!-- <li data-transition="fade" data-slotamount="10" data-masterspeed="1500"> <%#= image_tag 'home.jpg' %> -->
                  <!-- <img src="images/resource/slide-1.jpg" alt="slide 1"> -->
                    <!-- <div class="caption lfl stl"
                        data-x="center"
                        data-y="top"
                        data-hoffset="-100"
                        data-voffset="350"
                        data-speed="500"
                        data-start="1500"
                        data-easing="easeOutExpo">
                        <a href="#" class="btn btn-transparent">Register</a> 
                    </div>
                    <div class="caption lfr str"
                        data-x="center"
                        data-y="top"
                        data-hoffset="100"
                        data-voffset="350"
                        data-speed="500"
                        data-start="1500"
                        data-easing="easeOutExpo"><a href="#" class="btn btn-transparent">Login</a> 
                    </div> -->
                <!-- </li> -->
            </ul>
        </div>
    </article>
    <article class="focus-area bg-theme">
        <div class="container" id="main-form">
            <% if user_signed_in? %>
                <p class="pull-left">Terima kasih atas kunjungannya.....</p>
                <%= link_to destroy_user_session_path,class: "btn btn-transparent pull-right",  method: :delete do %>Logout<% end %>
            <% else %>
                <p class="pull-left">Sudah terdaftar menjadi alumni Assalaam?</p>
                <a href="<%= user_session_path %>" class="btn btn-transparent pull-right">Silahkan Login</a>
            <% end %>
            
        </div>
    </article>
    <footer>
        <div class="container">
        </div>
    </footer>
</div>
<!-- /pageWrapper --> 

<!-- <script src="js/jquery-1.10.2.min.js"></script>  -->
<!-- <script src="js/jquery-ui-1.10.3.custom.min.js"></script>  -->
<!-- <script src="js/jquery.carouFredSel-6.2.1-packed.js"></script>  -->
<!-- <script src="js/jquery.appear.js"></script>  -->
<!-- <script src="js/jquery.prettyPhoto.js"></script>  -->

<!-- revolution slider --> 
<!-- <script src="js/jquery.themepunch.revolution.min.js"></script>  -->
<script type="text/javascript">
    var tpj=jQuery;
    tpj.noConflict();
    tpj(document).ready(function() {
    if (tpj.fn.cssOriginal!=undefined)
    tpj.fn.css = tpj.fn.cssOriginal;

    tpj('.fullwidthbanner').revolution(
      {
        delay:9000,
        startwidth:1170,
        startheight:540,

        onHoverStop:"off",            // Stop Banner Timet at Hover on Slide on/off

        thumbWidth:100,             // Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
        thumbHeight:50,
        thumbAmount:3,

        hideThumbs:0,
        navigationType:"bullet",        // bullet, thumb, none
        navigationArrows:"solo",        // nexttobullets, solo (old name verticalcentered), none

        navigationStyle:"round",        // round,square,navbar,round-old,square-old,navbar-old, or any from the list in the docu (choose between 50+ different item), custom


        navigationHAlign:"center",        // Vertical Align top,center,bottom
        navigationVAlign:"bottom",          // Horizontal Align left,center,right
        navigationHOffset:0,
        navigationVOffset:20,

        soloArrowLeftHalign:"left",
        soloArrowLeftValign:"center",
        soloArrowLeftHOffset:20,
        soloArrowLeftVOffset:0,

        soloArrowRightHalign:"right",
        soloArrowRightValign:"center",
        soloArrowRightHOffset:20,
        soloArrowRightVOffset:0,

        touchenabled:"on",            // Enable Swipe Function : on/off



        stopAtSlide:-1,             // Stop Timer if Slide "x" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.
        stopAfterLoops:-1,            // Stop Timer if All slides has been played "x" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic

        hideCaptionAtLimit:0,         // It Defines if a caption should be shown under a Screen Resolution ( Basod on The Width of Browser)
        hideAllCaptionAtLilmit:0,       // Hide all The Captions if Width of Browser is less then this value
        hideSliderAtLimit:0,          // Hide the whole slider, and stop also functions if Width of Browser is less than this value


        fullWidth:"on",
        shadow:0                //0 = no Shadow, 1,2,3 = 3 Different Art of Shadows -  (No Shadow in Fullwidth Version !)

      });
});
</script> 

<!-- <script src="js/script.js"></script> -->
<%= javascript_include_tag "bootstrap.min" %>

app/views/javascript/_authenticate.js.erb
$( "div#main-form" ).html( "<%= escape_javascript(render 'form/authenticate') %>" );

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="container">
        <div class="row">
          <div class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong><%= content_tag :div, msg, :class => "flash_#{name}" %></strong> 
          </div>
        </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="menu">
    <li class="current-menu-item">
        <a href="<%= root_path %>" data-dup="Home">Home</a>
    </li>
    <% if user_signed_in? %>
        <li>
            <%= link_to users_path do %>Usrs<% end %>
        </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Info Alumni Jakarta</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield(:css_plugin) %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/list/_users.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading c-list">
                <span class="title">Member Of Alphabob</span>
                <!-- <ul class="pull-right c-controls">
                    <li><a href="#cant-do-all-the-work-for-you" data-toggle="tooltip" data-placement="top" title="Add Contact"><i class="glyphicon glyphicon-plus"></i></a></li>
                    <li><a href="#" class="hide-search" data-command="toggle-search" data-toggle="tooltip" data-placement="top" title="Toggle Search"><i class="fa fa-ellipsis-v"></i></a></li>
                </ul> -->
            </div>
            
            <!-- <div class="row" style="display: none;">
                <div class="col-xs-12">
                    <div class="input-group c-search">
                        <input type="text" class="form-control" id="contact-list-search">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search text-muted"></span></button>
                        </span>
                    </div>
                </div>
            </div> -->
            
            <ul class="list-group" id="contact-list">
                <% @users.each do  |user| %>
                    <li class="list-group-item">
                        <div class="col-xs-12 col-sm-3">
                            <%= image_tag "logo_opppmia.jpg" %>
                            <!-- <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="Scott Stevens" class="img-responsive img-circle" /> -->
                        </div>
                        <div class="col-xs-12 col-sm-9">
                            <span class="name"><%= user.name %></span><br/>
                            <span class="name">Pekerjaan : <%= user.current_job %></span><br/>
                            <span class="glyphicon glyphicon-map-marker text-muted c-info" data-toggle="tooltip" title="<%= user.address %>"></span>
                            <span class="visible-xs"> <span class="text-muted"><%= user.address %></span><br/></span>
                            <span class="glyphicon glyphicon-earphone text-muted c-info" data-toggle="tooltip" title="<%= user.phone %>"></span>
                            <span class="visible-xs"> <span class="text-muted"><%= user.phone %></span><br/></span>
                            <span class="fa fa-comments text-muted c-info" data-toggle="tooltip" title="<%= user.email %>"></span>
                            <span class="visible-xs"> <span class="text-muted"><%= user.email %></span><br/></span>
                        </div>
                        <div class="clearfix"></div>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% content_for :css_plugin do %>
    <style type="text/css">
        @import url(//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css);
        /*body {
            padding: 30px 0px 60px;
        }*/
        .panel > .list-group .list-group-item:first-child {
            /*border-top: 1px solid rgb(204, 204, 204);*/
        }
        @media (max-width: 767px) {
            .visible-xs {
                display: inline-block !important;
            }
            .block {
                display: block !important;
                width: 100%;
                height: 1px !important;
            }
        }
        #back-to-bootsnipp {
            position: fixed;
            top: 10px; right: 10px;
        }
        .c-search > .form-control {
           border-radius: 0px;
           border-width: 0px;
           border-bottom-width: 1px;
           font-size: 1.3em;
           padding: 12px 12px;
           height: 44px;
           outline: none !important;
        }
        .c-search > .form-control:focus {
            outline:0px !important;
            -webkit-appearance:none;
            box-shadow: none;
        }
        .c-search > .input-group-btn .btn {
           border-radius: 0px;
           border-width: 0px;
           border-left-width: 1px;
           border-bottom-width: 1px;
           height: 44px;
        }
        .c-list {
            padding: 0px;
            min-height: 44px;
        }
        .title {
            display: inline-block;
            font-size: 1.7em;
            font-weight: bold;
            padding: 5px 15px;
        }
        ul.c-controls {
            list-style: none;
            margin: 0px;
            min-height: 44px;
        }
        ul.c-controls li {
            margin-top: 8px;
            float: left;
        }
        ul.c-controls li a {
            font-size: 1.7em;
            padding: 11px 10px 6px;   
        }
        ul.c-controls li a i {
            min-width: 24px;
            text-align: center;
        }

        ul.c-controls li a:hover {
            background-color: rgba(51, 51, 51, 0.2);
        }

        .c-toggle {
            font-size: 1.7em;
        }
        .name {
            font-size: 1.7em;
            font-weight: 700;
        }
        .c-info {
            padding: 5px 10px;
            font-size: 1.25em;
        }
    </style>
<% end %>
<div class="pageWrapper">
    <article class="logo-bar">
        <div class="container"> 
            <%= render "layouts/messages" %>
            <div class="pull-right"> <span class="nav-button"></span>
                <nav class="main-nav">
                    <%= render "layouts/navigation" %>
                </nav>
            </div>
        </div>
    </article>
    <div class="fullwidthbanner">
        <%= render "list/users" %>
        <div id="cant-do-all-the-work-for-you" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="mySmallModalLabel">Ooops!!!</h4>
                </div>
                <div class="modal-body">
                    <p>I am being lazy and do not want to program an "Add User" section into this snippet... So it looks like you'll have to do that for yourself.</p><br/>
                    <p><strong>Sorry<br/>
                    ~ Mouse0270</strong></p>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
<!-- JavaScrip Search Plugin -->
<script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>
<%= javascript_include_tag "bootstrap.min" %>
</div>
<script type="text/javascript">
    $(function () {
    /* BOOTSNIPP FULLSCREEN FIX */
    if (window.location == window.parent.location) {
        $('#back-to-bootsnipp').removeClass('hide');
    }
    
    
    $('[data-toggle="tooltip"]').tooltip();
    
    $('#fullscreen').on('click', function(event) {
        event.preventDefault();
        window.parent.location = "http://bootsnipp.com/iframe/4l0k2";
    });
    $('a[href="#cant-do-all-the-work-for-you"]').on('click', function(event) {
        event.preventDefault();
        $('#cant-do-all-the-work-for-you').modal('show');
    })
    
    $('[data-command="toggle-search"]').on('click', function(event) {
        event.preventDefault();
        $(this).toggleClass('hide-search');
        
        if ($(this).hasClass('hide-search')) {        
            $('.c-search').closest('.row').slideUp(100);
        }else{   
            $('.c-search').closest('.row').slideDown(100);
        }
    })
    
    $('#contact-list').searchable({
        searchField: '#contact-list-search',
        selector: 'li',
        childSelector: '.col-xs-12',
        show: function( elem ) {
            elem.slideDown(100);
        },
        hide: function( elem ) {
            elem.slideUp( 100 );
        }
    })
});

</script>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>